name: Запит у команду
description: Оберіть командудо якої потрібен доступ
labels: ["access-request"]
body:
  - type: dropdown
    id: team
    attributes:
      label: Команда
      options:
        - cs-31
        - cs-32
    validations:
      required: true
